apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harako-takumi
  annotations:
    github.com/project-slug: harako-takumi/harako-takumi
spec:
  type: other
  lifecycle: unknown
  owner: sre
